import type { DictKey } from './dict-de';

/** Türkische Texte der Oberfläche. Exakt dieselben Schlüssel und Platzhalter wie dict-de.ts (der Typ erzwingt das). */
export const tr: Record<DictKey, string> = {
  // Genel
  'app.name': 'Borsa',
  'app.description': 'Hisseler sade dille: BIST, ABD ve XETRA için fiyatlar, değerlendirme ve haberler',
  'common.loading': 'Yükleniyor …',
  'common.retry': 'Tekrar dene',
  'common.back': '‹ Geri',
  'common.toList': 'Hisselerime git',
  'common.none': 'yok',
  'common.cancel': 'Vazgeç',
  'common.save': 'Kaydet',
  'app.notFound': 'Sayfa bulunamadı.',
  'app.crash': 'Uygulamada beklenmeyen bir hata oluştu.',
  'app.reload': 'Uygulamayı yeniden yükle',
  'banner.unauthorized': 'Erişim kodu eksik veya yanlış.',
  'banner.openSettings': 'Ayarları aç',
  'nav.aria': 'Ana gezinme',
  'nav.watchlist': 'Hisselerim',
  'nav.depot': 'Portföyüm',
  'nav.search': 'Ara',
  'nav.settings': 'Ayarlar',

  // Hatalar
  'error.generic': 'Bir şeyler ters gitti.',
  'error.NETWORK': 'Sunucuya bağlanılamadı.',
  'error.NETWORK.hint': 'İnternet bağlantını kontrol et.',
  'error.UNAUTHORIZED': 'Erişim kodu eksik veya yanlış.',
  'error.UNAUTHORIZED.hint': 'Ayarlar bölümüne doğru erişim kodunu gir.',
  'error.RATE_LIMITED': 'Şu anda çok fazla istek var.',
  'error.RATE_LIMITED.hint': 'Bir dakika sonra tekrar dene.',
  'error.NOT_FOUND': 'Veri kaynağı bu hisseyi tanımıyor.',
  'error.NOT_FOUND.hint': 'Kodu kontrol et, örneğin THYAO.IS veya AAPL.',
  'error.BLOCKED': 'Veri kaynağı isteği reddetti.',
  'error.BLOCKED.hint': 'Bu genellikle geçicidir. Biraz sonra tekrar dene.',
  'error.UPSTREAM': 'Veri kaynağına şu anda ulaşılamıyor.',
  'error.UPSTREAM.hint': 'Biraz sonra tekrar dene.',
  'error.BAD_RESPONSE': 'Veri kaynağı kullanılamaz veri gönderdi.',
  'error.BAD_RESPONSE.hint': 'Biraz sonra tekrar dene.',
  'error.BAD_REQUEST': 'İstek geçersizdi.',
  'error.AI_NOT_CONFIGURED': 'Yapay zekâ değerlendirmesi henüz kurulmadı.',
  'error.INTERNAL': 'Sunucuda bir hata oluştu.',
  'error.invalidTicker': 'Geçersiz kod: “{ticker}”',

  // Güncellik ve borsa durumu
  'fresh.realtime': 'Canlı',
  'fresh.delayed': 'yaklaşık {minutes} dk gecikmeli',
  'fresh.eod': 'Günün kapanış fiyatı',
  'market.open': 'Borsa açık',
  'market.closed': 'Borsa kapalı',
  'market.closedShort': 'kapalı',

  // Zaman
  'time.justNow': 'az önce',
  'time.minAgo': '{n} dk önce',
  'time.hourAgo': '{n} sa önce',
  'time.dayAgo': '{n} gün önce',
  'time.daysAgo': '{n} gün önce',

  // Hisselerim
  'watch.title': 'Hisselerim',
  'watch.edit': 'Düzenle',
  'watch.done': 'Bitti',
  'watch.addAria': 'Hisse ekle',
  'watch.list': 'Hisseler',
  'watch.emptyTitle': 'Henüz hisse yok',
  'watch.emptyText': 'Bir hisse ara ya da örnek bir listeyle başla (BIST, ABD, XETRA).',
  'watch.searchBtn': 'Hisse ara',
  'watch.exampleBtn': 'Örnek liste ekle',
  'watch.removeAria': '{symbol} hissesini kaldır',
  'watch.unknown': 'Bilinmiyor',
  'watch.unavailable': 'Alınamadı',
  'watch.loadingAria': 'Yükleniyor',
  'watch.updating': 'Güncelleniyor …',
  'watch.updatedAt': 'Güncelleme: {time}',
  'watch.updateFailed': 'Güncelleme başarısız',
  'watch.disclaimer': 'Yatırım tavsiyesi değildir. BIST ve XETRA fiyatları yaklaşık 15 dakika gecikmelidir.',

  // Fonlarım
  'watch.fundsTitle': 'Fonlarım',
  'watch.fundsAddAria': 'Fon ekle',
  'watch.fundsList': 'Fonlar',
  'watch.fundsEmpty': 'Listede henüz fon yok.',
  'watch.fundsSearchBtn': 'Fon ara',
  'watch.fundRemoveAria': '{code} kaldır',
  'watch.fundsDisclaimer': 'Yatırım tavsiyesi değildir. TEFAS fonları borsa kapandıktan sonra günde bir kez değerlenir.',

  // Arama
  'search.title': 'Ara',
  'search.placeholder': 'İsim veya kod, örn. THYAO, Apple, SAP',
  'search.aria': 'Hisse ara',
  'search.hint': 'Borsa İstanbul (BIST), XETRA ve ABD borsalarında arar.',
  'search.loading': 'Aranıyor …',
  'search.noResults': '“{term}” için sonuç yok.',
  'search.results': 'Arama sonuçları',
  'search.addAria': '{symbol} hissesini listeye ekle',
  'search.removeAria': '{symbol} hissesini listeden çıkar',
  'search.tabStocks': 'Hisseler',
  'search.tabFunds': 'Fonlar',
  'search.fundPlaceholder': 'Fon kodu veya adı, örn. AFT, YAY',
  'search.fundAria': 'Fon ara',
  'search.fundHint': 'TEFAS’taki Türk yatırım ve emeklilik fonlarında arar.',
  'search.fundAddAria': '{code} fonunu listeye ekle',
  'search.fundRemoveAria': '{code} fonunu listeden çıkar',
  'market.BIST': 'Borsa İstanbul',
  'market.XETRA': 'XETRA (Almanya)',
  'market.US': 'ABD',

  // Ayrıntı sayfası
  'detail.inList': '★ Listemde',
  'detail.addToList': '☆ Listeye ekle',
  'detail.asOf': 'Zaman: {time} (borsa saati)',
  'detail.dayLow': 'Bugünkü en düşük fiyat',
  'detail.dayHigh': 'Bugünkü en yüksek fiyat',
  'detail.prevClose': 'Dünkü kapanış',
  'detail.volume': 'İşlem gören adet',
  'detail.tabsAria': 'Görünüm',
  'tab.overview': 'Özet',
  'tab.news': 'Haberler',
  'tab.alerts': 'Alarmlar',
  'alerts.title': 'Bildirimler yakında geliyor',
  'alerts.text':
    'Planlanan: Fiyat belirlediğin sınıra ulaştığında, hisse sert düştüğünde veya yükseldiğinde ya da önemli bir şirket haberi çıktığında telefonuna bildirim gelecek. Her hisse için ayrı ayrı açılıp kapatılabilecek ve yalnızca borsa açıkken çalışacak.',

  // Değerlendirme (trafik ışığı)
  'verdict.title': 'Kısa özet',
  'verdict.bullish': 'Görünüm olumlu',
  'verdict.neutral': 'Karışık görünüm',
  'verdict.bearish': 'Görünüm zayıf',
  'verdict.sure': 'Tablo ne kadar net? {level}',
  'confidence.niedrig': 'pek net değil',
  'confidence.mittel': 'orta',
  'confidence.hoch': 'oldukça net',
  'verdict.pros': 'Lehte olanlar',
  'verdict.cons': 'Aleyhte olanlar',
  'verdict.note': 'Şimdiye kadarki fiyat hareketine dayanan otomatik bir değerlendirmedir. Alma veya satma tavsiyesi değildir.',
  'ai.creating': 'Değerlendirme hazırlanıyor …',
  'ai.created': 'Hazırlanma: {when}',
  'ai.demo': 'Demo',
  'ai.cached': 'kayıtlı sonuç',
  'ai.refresh': 'Yeniden değerlendir',
  'ai.refreshing': 'Hesaplanıyor …',
  'ai.demoBanner': 'Demo modu: gerçek yapay zekâ olmadan yer tutucu metinler. Henüz bir yapay zekâ anahtarı kurulmadı.',
  'ai.notConfiguredTitle': 'Yapay zekâ değerlendirmesi henüz kurulmadı.',
  'ai.notConfiguredText': '“Bir bakışta” bölümü yine de çalışır. Yapay zekâ metni için sunucuya ücretsiz bir Gemini anahtarı (GEMINI_API_KEY) girilmelidir, bkz. README.',
  'ai.notes': 'Değerlendirmeyle ilgili notlar',
  'ai.technical': 'Yapay zekâ sağlayıcısı: {provider} ({model})',
  'ai.removed': 'Dayanağı olmayan sayılar içeren {count} ifade kaldırıldı',
  'ai.empty': 'Bilgi yok (dayanağı olmayan sayılar içeren ifadeler kaldırıldı).',

  // Bir bakışta
  'glance.title': 'Bir bakışta',
  'glance.trendUp': 'Fiyat birkaç haftadır genel olarak yukarı yönlü.',
  'glance.trendDown': 'Fiyat birkaç haftadır genel olarak aşağı yönlü.',
  'glance.trendSide': 'Fiyat birkaç haftadır aşağı yukarı yatay seyrediyor.',
  'glance.above200': 'Fiyat, son yaklaşık 10 ayın ortalamasının {pct} üzerinde. Bu, güçlü bir işaret sayılır.',
  'glance.below200': 'Fiyat, son yaklaşık 10 ayın ortalamasının {pct} altında. Bu, zayıf bir işaret sayılır.',
  'glance.range': 'Geçen yıl fiyat {low} ile {high} arasında hareket etti. Şu an en yüksek seviyenin {pct} altında, en düşük seviyenin {pctLow} üzerinde.',
  'glance.nearHigh': 'Geçen yıl fiyat {low} ile {high} arasında hareket etti. Şu an en yüksek seviyeye yakın.',
  'glance.swing': 'Fiyat normal bir günde yaklaşık {pct} oynuyor. Bu, {level}.',
  'glance.swingCalm': 'oldukça sakin',
  'glance.swingNormal': 'ortalama düzeyde',
  'glance.swingWild': 'oldukça dalgalı',
  'glance.hot': 'Fiyat son zamanlarda çok hızlı yükseldi. Ardından çoğu zaman bir duraklama ya da küçük bir geri çekilme gelir.',
  'glance.cold': 'Fiyat son zamanlarda çok hızlı düştü. Bazen toparlanma gelir, bazen de düşüş sürer.',
  'glance.loading': 'Hesaplanıyor …',

  // Grafik
  'chart.aria': 'Fiyat grafiği',
  'chart.candleAria': 'Mum grafiği',
  'chart.period': 'Dönem',
  'chart.loading': 'Fiyatlar yükleniyor …',
  'chart.noData': 'Bu dönem için fiyat verisi yok (borsa kapalı veya tatil).',
  'chart.change': 'Dönem içindeki değişim',
  'chart.high': 'En yüksek seviye',
  'chart.low': 'En düşük seviye',
  'chart.currency': 'Gösterim para birimi',
  'chart.currencyNote': 'Günlük {currency}/TRY kuruyla çevrildi. Göstergelerle ilgili bilgiler hâlâ Türk lirası üzerinden hesaplanır.',
  'tf.1T': 'Gün',
  'tf.1W': 'Hafta',
  'tf.1M': 'Ay',
  'tf.6M': '6 Ay',
  'tf.1J': '1 Yıl',
  'tf.5J': '5 Yıl',
  'cur.TRY': '₺ Lira',
  'cur.USD': '$ Dolar',
  'cur.EUR': '€ Euro',

  // Lira etkisi
  'fx.title': 'Lira etkisi',
  'fx.text': 'Türk lirası yıllardır değer kaybediyor. Bu yüzden lira cinsinden kazançlar gerçekte olduğundan büyük görünür. Hisse şöyle bir performans gösterdi:',
  'fx.period.3 Monate': 'Son 3 ay',
  'fx.period.6 Monate': 'Son 6 ay',
  'fx.period.1 Jahr': 'Son 1 yıl',
  'fx.lira': 'lira cinsinden',
  'fx.weaker': '1 {currency} artık başlangıca göre {pct} daha fazla lira ediyor.',
  'fx.stronger': '1 {currency} artık başlangıca göre {pct} daha az lira ediyor.',
  'fx.USD': 'dolar',
  'fx.EUR': 'euro',
  'fx.inUSD': 'dolar cinsinden',
  'fx.inEUR': 'euro cinsinden',

  // İleri düzey ayrıntılar
  'adv.title': 'İleri düzey ayrıntılar',
  'adv.subtitle': 'Mum grafiği, işlem planı ve göstergeler, açıklamalarıyla',
  'adv.candles': 'Mum grafiği',
  'adv.candlesHelp': 'Her mum bir işlem gününü veya zaman dilimini gösterir: yeşil = fiyat yükseldi, kırmızı = düştü.',
  'adv.indicators': 'Çizgiler ve göstergeler',
  'adv.dailyOnly': 'Çizgiler günlük mumlardan hesaplanır: 6 Ay veya 1 Yıl seç.',
  'adv.source': 'Kaynak: {source}{approx} · Mumlar: {interval}',
  'adv.approx': ' (yaklaşık)',
  'adv.dropped': ' · {count} eksik mum atlandı',
  'legend.open': 'Açılış',
  'legend.high': 'Yüksek',
  'legend.low': 'Düşük',
  'legend.close': 'Kapanış',
  'legend.volume': 'Hacim',
  'chip.volume': 'Hacim',

  // İşlem planı
  'plan.title': 'Olası işlem planı (teknik)',
  'plan.intro': 'Şimdiye kadarki fiyat hareketinden yola çıkarak bir girişin nasıl görünebileceğine dair hesaplı bir örnek. Bu bir tavsiye değildir.',
  'plan.entry': 'Olası giriş',
  'plan.entryHint': 'Teknik açıdan alım yapmanın anlamlı olabileceği fiyat aralığı',
  'plan.stop': 'Zarar sınırı (stop-loss)',
  'plan.stopHint': 'Fiyat düşerse kaybı sınırlamak için belirlenen satış seviyesi',
  'plan.target': 'Olası hedef fiyat {n}',
  'plan.targets': 'Olası hedef fiyatlar',
  'plan.riskReward': 'Kazanç fırsatının riske oranı',
  'plan.riskRewardHint': 'Giriş, zarar sınırı ve ilk hedeften yapılan salt bir hesap, tahmin değildir.',
  'plan.notComputable': 'hesaplanamıyor',
  'plan.horizon': 'Vade',
  'plan.noEntry': 'giriş mantıklı görünmüyor',
  'plan.noStop': 'belirlenmedi',
  'plan.vsPrice': 'Güncel fiyata göre {pct}',
  'horizon.kurzfristig': 'kısa vade (günler)',
  'horizon.mittelfristig': 'orta vade (haftalar)',
  'horizon.langfristig': 'uzun vade (aylar)',
  'cand.entry_now': 'Güncel fiyat aralığı',
  'cand.entry_pullback': '{zone} destek bölgesine geri çekilme',
  'cand.entry_breakout': '{zone} direnç bölgesinin üzerine çıkış',
  'cand.stop_atr': 'Fiyatın biraz altı (ortalama günlük hareketin 2 katı)',
  'cand.stop_support': '{zone} destek bölgesinin altı',
  'cand.stop_breakout': 'Aşılan {zone} direncinin altı',
  'cand.target_zone': '{zone} direnç bölgesi (alt sınır)',
  'cand.target_high52': 'Son 52 haftanın en yüksek seviyesi',
  'cand.target_atr2': 'Hesaba göre fiyatın 2 günlük hareket kadar üzeri',
  'cand.target_atr4': 'Hesaba göre fiyatın 4 günlük hareket kadar üzeri',
  'cand.target_atr_high52': 'Hesaba göre yıllık zirvenin üzeri',
  'adv.analysis': 'Ayrıntılı değerlendirme',
  'adv.forTitle': 'Giriş lehine gerekçeler',
  'adv.againstTitle': 'Aleyhine gerekçeler',
  'adv.risksTitle': 'Riskler',

  // Göstergeler
  'tech.title': 'Göstergeler',
  'tech.loading': 'Göstergeler hesaplanıyor …',
  'tech.dataHint': 'Veri notu',
  'tech.trend': 'Eğilim',
  'tech.trendStructure': 'Eğilim yapısı',
  'tech.trendStructureHint': 'Yükselen tepe ve dipler = yükseliş eğilimi, alçalan tepe ve dipler = düşüş eğilimi. Tepeler: {highs} · Dipler: {lows}',
  'tech.smaCross': 'Kısa ve uzun ortalama',
  'tech.smaCrossAbove': 'SMA 50, SMA 200’ün üzerinde',
  'tech.smaCrossBelow': 'SMA 50, SMA 200’ün altında',
  'tech.golden': '{date} tarihinde Golden Cross ({bars} mum önce)',
  'tech.death': '{date} tarihinde Death Cross ({bars} mum önce)',
  'tech.noCross': 'Veri döneminde kesişim yok',
  'tech.averages': 'Ortalama fiyatlar',
  'tech.averageRow': 'SMA {n} / EMA {n}',
  'tech.averageHint': 'Fiyat, SMA’ya göre {pct}',
  'tech.momentum': 'İvme',
  'tech.macdBullCross': '{bars} mum önce yükseliş kesişimi',
  'tech.macdBearCross': '{bars} mum önce düşüş kesişimi',
  'tech.histogram': 'Histogram {value}',
  'tech.volatility': 'Dalgalanma',
  'tech.bollingerHint': '%B {pb} · Bant genişliği {bw}',
  'tech.atrHint': 'Fiyatın {pct} kadarı (ortalama günlük hareket)',
  'tech.volumeTitle': 'İşlem hacmi',
  'tech.volumeTrend': 'Hacim eğilimi',
  'tech.volumeAvg': 'Ort. 20: {a} · Ort. 50: {b}',
  'tech.upDown': 'Yükselen ve düşen günlerdeki işlem (20 gün)',
  'tech.upDownHint': '1’in üzerinde: fiyatın yükseldiği günlerde daha çok işlem yapıldı',
  'tech.levels': 'Destek ve direnç',
  'tech.noLevels': 'Güvenilir bölge bulunamadı.',
  'tech.noResistance': 'Fiyatın üzerinde güvenilir bir direnç bölgesi yok (en az 2 temas).',
  'tech.nextObstacle': 'Sıradaki engel: son 52 haftanın en yüksek seviyesi, {high}.',
  'tech.nearHigh': 'Fiyat, veri dönemindeki zirveye yakın.',
  'level.R': 'Direnç {id}',
  'level.S': 'Destek {id}',
  'level.I': 'Bölge {id} (fiyat içinde)',
  'tech.touches': '{n} temas',
  'tech.touch1': '1 temas',
  'tech.range52': '52 haftalık aralık',
  'tech.range52Partial': '52 haftalık aralık (yalnızca {bars} mum)',
  'tech.high52': '52 haftalık zirve',
  'tech.low52': '52 haftalık dip',
  'tech.belowHigh': 'Fiyat {pct} altında',
  'tech.aboveLow': 'Fiyat {pct} üzerinde',
  'tech.footer': 'Tüm göstergeler günlük mumlardan program tarafından hesaplanır, yapay zekâ tahmin etmez. Son mum, borsa açıkken tamamlanmamış olabilir.',
  'trend.aufwärts': 'yukarı',
  'trend.abwärts': 'aşağı',
  'trend.seitwärts': 'yatay',
  'trend.unbekannt': 'bilinmiyor',
  'zone.überkauft': 'aşırı alım (sert yükseldi)',
  'zone.überverkauft': 'aşırı satım (sert düştü)',
  'zone.neutral': 'nötr',
  'zone.unbekannt': 'bilinmiyor',
  'macd.über Signal': 'sinyal çizgisinin üzerinde',
  'macd.unter Signal': 'sinyal çizgisinin altında',
  'macd.unbekannt': 'bilinmiyor',
  'vol.steigend': 'artıyor',
  'vol.fallend': 'azalıyor',
  'vol.neutral': 'sabit',
  'vol.unbekannt': 'bilinmiyor',
  'hint.rsi': 'Fiyatın son zamanlarda ne kadar hızlı yükseldiğini veya düştüğünü ölçer. 70 üzeri “aşırı ısınmış”, 30 altı “sert düşmüş” sayılır.',
  'hint.macd': 'Kısa vadeli eğilimi uzun vadeli eğilimle karşılaştırır. Değer sinyal çizgisinin üzerindeyse ivme daha çok olumludur.',
  'hint.bollinger': 'Ortalama fiyatın etrafındaki bir bant. Fiyat kenara değerse ortalamadan alışılmadık ölçüde uzaklaşmış demektir.',
  'hint.atr': 'Fiyatın bir günde tipik olarak ne kadar oynadığı.',
  'hint.sma': 'Son 20, 50 veya 200 işlem gününün ortalama fiyatı (SMA basit ortalama, EMA ağırlıklı: yeni günler daha çok sayılır).',

  // Sözlük
  'gloss.title': 'Terimler ne anlama geliyor?',
  'gloss.sma': 'SMA / EMA: Son günlerin ortalama fiyatı. Fiyatın ortalamanın üzerine çıkması güç işareti sayılır.',
  'gloss.rsi': 'RSI: 0 ile 100 arasında bir sayı. 70 üzerinde fiyat son zamanlarda çok hızlı yükselmiş, 30 altında çok hızlı düşmüş demektir.',
  'gloss.macd': 'MACD: Fiyatın ivmesini göstermek için iki ortalamayı karşılaştırır.',
  'gloss.bollinger': 'Bollinger bantları: Ortalama fiyatın etrafında, fiyatın genelde ne kadar saptığını gösteren bir bant.',
  'gloss.atr': 'ATR: Ortalama günlük hareket aralığı, yani fiyatın bir günde ne kadar oynadığı.',
  'gloss.support': 'Destek / direnç: Fiyatın geçmişte sık sık yön değiştirdiği, yukarı ya da aşağı döndüğü fiyat bölgeleri.',
  'gloss.cross': 'Golden Cross / Death Cross: Kısa ortalamanın (50 gün) uzun ortalamayı (200 gün) yukarı veya aşağı doğru kesmesi.',
  'gloss.stop': 'Stop-loss: Kaybı sınırlamak için kendi belirlediğin satış seviyesi.',
  'gloss.volume': 'Hacim: Kaç hisse işlem gördüğü. Yüksek hacim, fiyat hareketini daha güvenilir kılar.',

  // Haberler
  'news.loading': 'Haberler yükleniyor …',
  'news.rating': 'Yapay zekâ haberleri değerlendiriyor …',
  'news.summaryTitle': 'Kısaca',
  'news.noSummary': 'Özet mevcut değil.',
  'news.positive': 'Hisse için iyi',
  'news.negative': 'Hisse için kötü',
  'news.nothing': 'Haberlerde güvenilir bir şey yok.',
  'news.listTitle': 'Haberler',
  'news.noItems': 'Güncel haber bulunamadı.',
  'news.allNoise': 'Tüm haberler az önemli olarak sınıflandırıldı.',
  'news.showMore': 'Daha az önemli {n} haberi göster',
  'news.showMore1': 'Daha az önemli 1 haberi göster',
  'news.showLess': 'Daha az önemli haberleri gizle',
  'news.sourcesFailed': 'Tüm kaynaklara ulaşılamadı: {sources}. Liste eksik olabilir.',
  'news.footnote': 'Başka dillerdeki haberler yapay zekâ tarafından çevrilir (değerlendirme hazır olunca). Orijinali altında görünür.',
  'news.original': 'Orijinal',
  'news.kapTitle': 'Resmî bildirimler (KAP)',
  'news.kapText': 'Şirketin resmî KAP platformunda yaptığı zorunlu bildirimler. En güvenilir kaynaktır ve değerlendirmede en çok ağırlığı taşır.',
  'news.pressTitle': 'Basın',
  'news.pressText': 'Basında çıkan haberler. Resmî bildirimleri tamamlar, ancak çoğu zaman yorum ya da tekrardır.',
  'news.noKap': 'Bu dönemde resmî KAP bildirimi olmadı.',
  'news.alsoReported': '+{n} haber daha',
  'news.sortHint': 'Hisse üzerindeki olası etkiye göre sıralı, en önemliler önce.',
  'news.tapHint': 'Bir habere dokun: Yapay zekâ haberi açıklar ve hisse için ne anlama gelebileceğini değerlendirir.',
  'item.back': '‹ Tüm haberler',
  'item.reading': 'Yapay zekâ haberi okuyor …',
  'item.gone': 'Bu haber artık listede yok. Geri dön ve yeniden seç.',
  'item.summary': 'Kısaca anlatım',
  'item.impact': 'Hisse için ne anlama gelebilir',
  'item.short': 'Kısa vadede (günler ile haftalar)',
  'item.long': 'Uzun vadede (aylar ile yıllar)',
  'item.positives': 'Yardımcı olabilecekler',
  'item.negatives': 'Baskı yaratabilecekler',
  'item.watch': 'Nelere dikkat edebilirsin',
  'item.basisFull': 'Dayanak: KAP bildiriminin tam metni.',
  'item.basisHeadline': 'Dayanak: yalnızca başlık (varsa kısa metin). Haberin kendisi yapay zekâya sunulmadı, bu yüzden değerlendirme kabadır.',
  'item.certainty': 'Değerlendirme ne kadar sağlam dayanıyor? {level}',
  'item.note': 'Bu, olası etkilerin bir değerlendirmesidir; fiyat tahmini ya da alma veya satma tavsiyesi değildir.',
  'item.openKap': 'Bildirimi KAP’ta aç ↗',
  'item.openOriginal': 'Orijinal haberi aç ↗',
  'impact.positiv': 'Hisse için olumlu görünüyor',
  'impact.neutral': 'Hisse için nötr görünüyor',
  'impact.negativ': 'Hisse için olumsuz görünüyor',
  'certainty.niedrig': 'zayıf',
  'certainty.mittel': 'orta',
  'certainty.hoch': 'sağlam',
  'news.kapHint': 'Şirketin resmî zorunlu bildirimi (KAP)',
  'news.category': 'Bildirim',
  'sent.positiv': 'Olumlu',
  'sent.neutral': 'Nötr',
  'sent.negativ': 'Olumsuz',
  'news.important': 'Önemli',
  'news.sentimentUp': 'Olumlu',
  'news.sentimentDown': 'Olumsuz',

  // Ayarlar
  'settings.title': 'Ayarlar',
  'settings.language': 'Dil',
  'settings.languageHint': 'Tüm uygulama ve yapay zekâ metinleri için geçerlidir.',
  'settings.access': 'Erişim',
  'settings.tokenLabel': 'Erişim kodu (verilerini korur, yalnızca bu cihazda saklanır)',
  'settings.tokenPlaceholder': 'Belirlenmediyse boş bırak',
  'settings.saveTest': 'Kaydet ve bağlantıyı test et',
  'settings.testing': 'Test ediliyor …',
  'settings.connectionOk': 'Bağlantı tamam',
  'settings.tokenAccepted': ' (kod kabul edildi)',
  'settings.noTokenNeeded': ' (kod gerekmiyor)',
  'settings.exampleQuote': ', örnek fiyat AAPL: {price}',
  'settings.connectionFailed': 'Bağlantı başarısız',
  'settings.checkToken': ' Lütfen erişim kodunu kontrol et.',
  'settings.aiTitle': 'Yapay zekâ değerlendirmesi',
  'settings.aiActive': 'Etkin: {providers}',
  'settings.aiDemo': '(demo modu, gerçek yapay zekâ değil)',
  'settings.aiMissing': 'Kurulmadı. Sunucuda yapay zekâ anahtarı eksik (GEMINI_API_KEY veya GROQ_API_KEY).',
  'settings.aiStorageSupabase': 'Önbellek: Supabase (kalıcı).',
  'settings.aiStorageMemory': 'Önbellek: yalnızca sunucunun belleği.',
  'settings.aiStorageWarn': ' Supabase olmadan değerlendirmeler soğuk başlangıçlarda kaybolur ve ücretsiz kotayı daha hızlı tüketir.',
  'settings.backupTitle': 'Listemi yedekle',
  'settings.backupText':
    'Hisse listen bu tarayıcıda veya yüklü uygulamada duruyor ({count}). Ana ekrandaki uygulamanın ayrı bir hafızası vardır: listeyi Safari tarayıcısında dışa aktar, uygulamada içe aktar.',
  'settings.exportBtn': 'Dışa aktar (kopyala)',
  'settings.importPlaceholder': 'Dışa aktarılan metni buraya yapıştır ve içe aktar',
  'settings.importAria': 'İçe aktarma metni',
  'settings.importBtn': 'İçe aktar (listenin yerine geçer)',
  'settings.copied': 'Liste panoya kopyalandı.',
  'settings.copyFailed': 'Kopyalanamadı: Metin aşağıda duruyor, oradan seçebilirsin.',
  'settings.imported': '{n} içe aktarıldı.',
  'settings.importFailed': 'Metin geçerli bir dışa aktarım değil. Hiçbir şey değiştirilmedi.',
  'settings.count.one': '1 hisse',
  'settings.count.many': '{n} hisse',
  'settings.aboutTitle': 'Veriler nereden geliyor?',
  'settings.about1': 'Fiyatlar ve mumlar: Yahoo Finance (resmî olmayan), kesintide İş Yatırım (BIST, yalnızca gün sonu), ABD canlı fiyatları isteğe bağlı olarak Finnhub üzerinden.',
  'settings.about2': 'BIST ve XETRA fiyatları yaklaşık 15 dakika gecikmelidir. BIST için ücretsiz gerçek zamanlı kaynak yoktur.',
  'settings.about3': 'Haberler: KAP (BIST şirketlerinin zorunlu bildirimleri) ve Google Haberler.',
  'settings.about4': 'Tüm göstergeler program tarafından hesaplanır. Yapay zekâ (Gemini, yedek olarak Groq) yalnızca açıklayıcı metni yazar ve sayı uyduramaz: fiyatları hesaplanmış önerilerden seçer, diğer sayılar girdi verilerine göre denetlenir.',
  'settings.about5': 'Fonlar: TEFAS (Tefas.gov.tr), Türkiye’deki yatırım ve emeklilik fonlarının resmî alım satım platformu. Fiyat, borsa kapandıktan sonra günde bir kez güncellenir, gerçek zamanlı değildir.',
  'settings.version': 'Sürüm 0.5 · sade görünüm, Almanca ve Türkçe',

  // Fon ayrıntı sayfası (TEFAS)
  'fund.category': 'Kategori',
  'fund.noCategory': 'Kategorisiz',
  'fund.price': 'Pay fiyatı',
  'fund.priceHint': 'Lira cinsinden pay başına net varlık değeri.',
  'fund.dailyChange': 'Bir önceki güne göre değişim',
  'fund.asOf': 'Tarih: {date}',
  'fund.freshness': 'TEFAS fiyatı borsa kapandıktan sonra günde bir kez günceller, gerçek zamanlı değildir.',
  'fund.rank': 'Kategorideki sırası',
  'fund.rankValue': '{count} fon içinde {rank}.',
  'fund.investors': 'Yatırımcı sayısı',
  'fund.marketShare': 'Tüm TEFAS fonları içindeki payı',
  'fund.benchmarkTitle': 'Karşılaştırma',
  'fund.benchmarkText': 'Fon, seçilen dönemde diğer yatırım araçlarına göre böyle bir performans gösterdi. Geçmişteki fiyat kazançları geleceğe dair bir şey söylemez.',
  'fund.kind.fund': 'Bu fon',
  'fund.kind.gold': 'Altın',
  'fund.kind.bist100': 'BIST 100',
  'fund.kind.bist30': 'BIST 30',
  'fund.kind.cpi': 'Enflasyon (TÜFE)',
  'fund.kind.usd': 'ABD Doları',
  'fund.kind.eur': 'Euro',
  'fund.kind.deposit': 'Mevduat faizi',
  'fund.p.week': 'Hafta',
  'fund.p.month': 'Ay',
  'fund.p.3month': '3 Ay',
  'fund.p.6month': '6 Ay',
  'fund.p.ytd': 'Yılbaşından İtibaren',
  'fund.p.year': '1 Yıl',
  'fund.p.3year': '3 Yıl',
  'fund.p.5year': '5 Yıl',
  'fund.disclaimer': 'Fiyatlar ve karşılaştırma verileri TEFAS’tan (Tefas.gov.tr) alınır, Türkiye’deki fonların resmî alım satım platformudur. Yatırım tavsiyesi değildir.',
  'error.fundNotFound': 'Bu fon TEFAS’ta bulunamadı.',

  // Portföy
  'depot.title': 'Portföyüm',
  'depot.value': 'Güncel değer',
  'depot.cost': 'Yatırılan sermaye',
  'depot.gain': 'Kâr/Zarar',
  'depot.empty': 'Portföyde henüz pozisyon yok.',
  'depot.emptyText': 'Portföyünün ne kadar değerinde olduğunu ve kârda mı zararda mı olduğunu görmek için ilk alımını ekle.',
  'depot.addBtn': 'Alım ekle',
  'depot.list': 'Pozisyonlar',
  'depot.removeAria': '{symbol} hissesini portföyden kaldır',
  'depot.quantity': 'Adet',
  'depot.avgPrice': 'Ort. alış fiyatı',
  'depot.currentPrice': 'Güncel fiyat',
  'depot.incompleteNote': 'En az bir pozisyon veya para birimi için şu an güncel kur yok: Bu yüzden toplam eksik hesaplanıyor.',
  'depot.convertedNote': 'Yabancı para birimleri güncel günlük kurla çevrilir.',
  'depot.disclaimer': 'Yatırım tavsiyesi değildir. Değerler senin girdiğin bilgilerden ve güncel fiyatlardan hesaplanır, garanti verilmez.',
  'depot.addTitle': 'Alım ekle',
  'depot.addFor': '{symbol} için alım gir',
  'depot.changeSelection': '‹ Başka hisse veya fon seç',
  'depot.holdingsTitle': 'Elimdeki miktar',
  'depot.holdingsEmpty': 'Portföyde henüz bir şey yok.',
  'depot.lotsTitle': 'Alımlar',
  'depot.removeLotAria': '{date} tarihli alımı kaldır',
  'depot.cashTitle': 'Nakit',
  'depot.cashEmpty': 'Henüz nakit girilmedi.',
  'depot.editCash': 'Nakdi düzenle',
  'depot.cashValue': 'Nakit',
  'depot.totalWealth': 'Toplam varlık',
  'lot.quantity': 'Adet',
  'lot.price': 'Birim alış fiyatı ({currency})',
  'lot.date': 'Alım tarihi',
  'lot.add': 'Ekle',

  // Uyarı
  'disclaimer.strong': 'Yatırım tavsiyesi değildir.',
  'disclaimer.text': 'Tüm bilgiler yalnızca bilgilendirme amaçlıdır, garanti verilmez ve gecikmeli ya da hatalı olabilir. Geçmişteki fiyat kazançları geleceğe dair bir şey söylemez.',
};
