/**
 * Deutsche Texte der Oberfläche. Platzhalter stehen in geschweiften Klammern. Die türkische Fassung (dict-tr.ts)
 * muss exakt dieselben Schlüssel und Platzhalter haben, das prüft der Typ und ein Test.
 * Ton: einfache Alltagssprache, "du", keine Fachbegriffe außerhalb des Bereichs "Details für Fortgeschrittene".
 */
export const de = {
  // Allgemein
  'app.name': 'Borsa',
  'app.description': 'Aktien einfach erklärt: Kurse, Einschätzung und Nachrichten für BIST, US und XETRA',
  'common.loading': 'Lädt …',
  'common.retry': 'Erneut versuchen',
  'common.back': '‹ Zurück',
  'common.toList': 'Zu meinen Aktien',
  'common.none': 'keine',
  'app.notFound': 'Seite nicht gefunden.',
  'app.crash': 'Unerwarteter Fehler in der App.',
  'app.reload': 'App neu laden',
  'banner.unauthorized': 'Der Zugangscode fehlt oder ist falsch.',
  'banner.openSettings': 'Einstellungen öffnen',
  'nav.aria': 'Hauptnavigation',
  'nav.watchlist': 'Meine Aktien',
  'nav.search': 'Suche',
  'nav.settings': 'Einstellungen',

  // Fehler
  'error.generic': 'Etwas ist schiefgelaufen.',
  'error.NETWORK': 'Keine Verbindung zum Server.',
  'error.NETWORK.hint': 'Prüfe deine Internetverbindung.',
  'error.UNAUTHORIZED': 'Der Zugangscode fehlt oder ist falsch.',
  'error.UNAUTHORIZED.hint': 'Trage in den Einstellungen den richtigen Zugangscode ein.',
  'error.RATE_LIMITED': 'Gerade sind zu viele Anfragen unterwegs.',
  'error.RATE_LIMITED.hint': 'Versuche es in einer Minute noch einmal.',
  'error.NOT_FOUND': 'Diese Aktie kennt die Datenquelle nicht.',
  'error.NOT_FOUND.hint': 'Prüfe das Kürzel, zum Beispiel THYAO.IS oder AAPL.',
  'error.BLOCKED': 'Die Datenquelle hat die Anfrage abgelehnt.',
  'error.BLOCKED.hint': 'Das ist meist nur vorübergehend. Versuche es später noch einmal.',
  'error.UPSTREAM': 'Die Datenquelle ist gerade nicht erreichbar.',
  'error.UPSTREAM.hint': 'Versuche es später noch einmal.',
  'error.BAD_RESPONSE': 'Die Datenquelle hat unbrauchbare Daten geliefert.',
  'error.BAD_RESPONSE.hint': 'Versuche es später noch einmal.',
  'error.BAD_REQUEST': 'Die Anfrage war ungültig.',
  'error.AI_NOT_CONFIGURED': 'Die KI-Einschätzung ist noch nicht eingerichtet.',
  'error.INTERNAL': 'Beim Server ist ein Fehler aufgetreten.',
  'error.invalidTicker': 'Ungültiges Kürzel: „{ticker}“',

  // Aktualität und Börsenstatus
  'fresh.realtime': 'Live',
  'fresh.delayed': 'ca. {minutes} Min. verzögert',
  'fresh.eod': 'Schlusskurs des Tages',
  'market.open': 'Börse offen',
  'market.closed': 'Börse geschlossen',
  'market.closedShort': 'geschlossen',

  // Zeitangaben
  'time.justNow': 'gerade eben',
  'time.minAgo': 'vor {n} Min.',
  'time.hourAgo': 'vor {n} Std.',
  'time.dayAgo': 'vor {n} Tag',
  'time.daysAgo': 'vor {n} Tagen',

  // Meine Aktien
  'watch.title': 'Meine Aktien',
  'watch.edit': 'Bearbeiten',
  'watch.done': 'Fertig',
  'watch.addAria': 'Aktie hinzufügen',
  'watch.list': 'Aktien',
  'watch.emptyTitle': 'Noch keine Aktien',
  'watch.emptyText': 'Suche eine Aktie oder starte mit einer Beispielliste (BIST, US, XETRA).',
  'watch.searchBtn': 'Aktie suchen',
  'watch.exampleBtn': 'Beispielliste hinzufügen',
  'watch.removeAria': '{symbol} entfernen',
  'watch.unknown': 'Unbekannt',
  'watch.unavailable': 'Nicht verfügbar',
  'watch.loadingAria': 'Lädt',
  'watch.updating': 'Aktualisiere …',
  'watch.updatedAt': 'Aktualisiert um {time}',
  'watch.updateFailed': 'Aktualisierung fehlgeschlagen',
  'watch.disclaimer': 'Keine Anlageberatung. Kurse von BIST und XETRA sind ca. 15 Minuten verzögert.',

  // Suche
  'search.title': 'Suche',
  'search.placeholder': 'Name oder Kürzel, z. B. THYAO, Apple, SAP',
  'search.aria': 'Aktie suchen',
  'search.hint': 'Durchsucht Borsa Istanbul (BIST), XETRA und die US-Börsen.',
  'search.loading': 'Suche …',
  'search.noResults': 'Keine Treffer für „{term}“.',
  'search.results': 'Suchergebnisse',
  'search.addAria': '{symbol} zur Liste hinzufügen',
  'search.removeAria': '{symbol} von der Liste entfernen',
  'market.BIST': 'Borsa Istanbul',
  'market.XETRA': 'XETRA (Deutschland)',
  'market.US': 'USA',

  // Detailseite
  'detail.inList': '★ Auf meiner Liste',
  'detail.addToList': '☆ Zur Liste',
  'detail.asOf': 'Stand {time} (Börsenzeit)',
  'detail.dayLow': 'Tiefster Preis heute',
  'detail.dayHigh': 'Höchster Preis heute',
  'detail.prevClose': 'Schlusskurs gestern',
  'detail.volume': 'Gehandelte Stücke',
  'detail.tabsAria': 'Ansicht',
  'tab.overview': 'Übersicht',
  'tab.news': 'Nachrichten',
  'tab.alerts': 'Alarme',
  'alerts.title': 'Benachrichtigungen kommen bald',
  'alerts.text':
    'Geplant: Du bekommst eine Nachricht aufs Handy, wenn der Preis eine Grenze erreicht, die Aktie stark fällt oder steigt oder eine wichtige Firmenmeldung erscheint. Alles pro Aktie ein- und ausschaltbar und nur, wenn die Börse geöffnet ist.',

  // Einschätzung (Ampel)
  'verdict.title': 'Kurzfazit',
  'verdict.bullish': 'Sieht eher gut aus',
  'verdict.neutral': 'Gemischtes Bild',
  'verdict.bearish': 'Sieht eher schwach aus',
  'verdict.sure': 'Wie klar ist das Bild? {level}',
  'confidence.niedrig': 'eher unklar',
  'confidence.mittel': 'mittel',
  'confidence.hoch': 'ziemlich klar',
  'verdict.pros': 'Das spricht dafür',
  'verdict.cons': 'Das spricht dagegen',
  'verdict.note': 'Automatische Einschätzung der bisherigen Kursentwicklung. Sie ist keine Empfehlung zum Kaufen oder Verkaufen.',
  'ai.creating': 'Die Einschätzung wird erstellt …',
  'ai.created': 'Erstellt {when}',
  'ai.demo': 'Demo',
  'ai.cached': 'aus dem Speicher',
  'ai.refresh': 'Neu auswerten',
  'ai.refreshing': 'Berechne …',
  'ai.demoBanner': 'Demo-Modus: Platzhaltertexte ohne echte KI. Es ist noch kein KI-Schlüssel eingerichtet.',
  'ai.notConfiguredTitle': 'KI-Einschätzung noch nicht eingerichtet.',
  'ai.notConfiguredText': 'Die Angaben „Auf einen Blick“ funktionieren trotzdem. Für den KI-Text muss auf dem Server ein kostenloser Gemini-Schlüssel (GEMINI_API_KEY) eingetragen werden, siehe README.',
  'ai.notes': 'Hinweise zur Auswertung',
  'ai.technical': 'KI-Anbieter: {provider} ({model})',
  'ai.removed': '{count} Aussage(n) mit nicht belegten Zahlen entfernt',
  'ai.empty': 'Keine Angabe (Aussagen ohne belegte Zahlen wurden entfernt).',

  // Auf einen Blick
  'glance.title': 'Auf einen Blick',
  'glance.trendUp': 'Der Kurs geht seit einigen Wochen eher nach oben.',
  'glance.trendDown': 'Der Kurs geht seit einigen Wochen eher nach unten.',
  'glance.trendSide': 'Der Kurs bewegt sich seit einigen Wochen ungefähr seitwärts.',
  'glance.above200': 'Der Kurs liegt {pct} über dem Durchschnitt der letzten rund 10 Monate. Das gilt als Zeichen von Stärke.',
  'glance.below200': 'Der Kurs liegt {pct} unter dem Durchschnitt der letzten rund 10 Monate. Das gilt als Zeichen von Schwäche.',
  'glance.range': 'Im letzten Jahr lag der Kurs zwischen {low} und {high}. Aktuell ist er {pct} unter dem Höchststand und {pctLow} über dem Tiefststand.',
  'glance.nearHigh': 'Im letzten Jahr lag der Kurs zwischen {low} und {high}. Aktuell liegt er nahe am Höchststand.',
  'glance.swing': 'Der Kurs schwankt an einem normalen Tag um etwa {pct}. Das ist {level}.',
  'glance.swingCalm': 'eher ruhig',
  'glance.swingNormal': 'durchschnittlich',
  'glance.swingWild': 'ziemlich unruhig',
  'glance.hot': 'Der Kurs ist zuletzt sehr schnell gestiegen. Danach folgt oft eine Pause oder ein kleiner Rücksetzer.',
  'glance.cold': 'Der Kurs ist zuletzt sehr schnell gefallen. Manchmal folgt eine Erholung, manchmal geht es aber auch weiter abwärts.',
  'glance.loading': 'Berechne …',

  // Diagramm
  'chart.aria': 'Kursverlauf',
  'chart.candleAria': 'Kerzenchart',
  'chart.period': 'Zeitraum',
  'chart.loading': 'Lade Kurse …',
  'chart.noData': 'Keine Kursdaten für diesen Zeitraum (Börse geschlossen oder Feiertag).',
  'chart.change': 'Veränderung im Zeitraum',
  'chart.high': 'Höchster Stand',
  'chart.low': 'Tiefster Stand',
  'chart.currency': 'Anzeige in',
  'chart.currencyNote': 'Umgerechnet mit dem Tageskurs {currency}/TRY. Die Angaben zu Kennzahlen beziehen sich weiterhin auf Lira.',
  'tf.1T': 'Tag',
  'tf.1W': 'Woche',
  'tf.1M': 'Monat',
  'tf.6M': '6 Mon.',
  'tf.1J': '1 Jahr',
  'tf.5J': '5 Jahre',
  'cur.TRY': '₺ Lira',
  'cur.USD': '$ Dollar',
  'cur.EUR': '€ Euro',

  // Lira-Effekt
  'fx.title': 'Der Lira-Effekt',
  'fx.text': 'Die türkische Lira verliert seit Jahren an Wert. Deshalb sehen Gewinne in Lira größer aus, als sie in Wirklichkeit sind. So hat sich die Aktie entwickelt:',
  'fx.period.3 Monate': 'Letzte 3 Monate',
  'fx.period.6 Monate': 'Letzte 6 Monate',
  'fx.period.1 Jahr': 'Letztes Jahr',
  'fx.lira': 'in Lira',
  'fx.weaker': 'Ein {currency} kostet jetzt {pct} mehr Lira als am Anfang.',
  'fx.stronger': 'Ein {currency} kostet jetzt {pct} weniger Lira als am Anfang.',
  'fx.USD': 'Dollar',
  'fx.EUR': 'Euro',
  'fx.inUSD': 'in Dollar',
  'fx.inEUR': 'in Euro',

  // Details für Fortgeschrittene
  'adv.title': 'Details für Fortgeschrittene',
  'adv.subtitle': 'Kerzenchart, Handelsplan und Kennzahlen, mit Erklärungen',
  'adv.candles': 'Kerzenchart',
  'adv.candlesHelp': 'Jede Kerze zeigt einen Handelstag oder Zeitabschnitt: grün = Kurs gestiegen, rot = gefallen.',
  'adv.indicators': 'Linien und Anzeigen',
  'adv.dailyOnly': 'Die Linien werden aus Tageskerzen berechnet: wähle 6 Mon. oder 1 Jahr.',
  'adv.source': 'Quelle: {source}{approx} · Kerzen: {interval}',
  'adv.approx': ' (angenähert)',
  'adv.dropped': ' · {count} unvollständige Kerzen übersprungen',
  'legend.open': 'Eröffnung',
  'legend.high': 'Hoch',
  'legend.low': 'Tief',
  'legend.close': 'Schluss',
  'legend.volume': 'Volumen',
  'chip.volume': 'Volumen',

  // Handelsplan
  'plan.title': 'Möglicher Handelsplan (technisch)',
  'plan.intro': 'Ein Rechenbeispiel aus dem bisherigen Kursverlauf, wie ein Einstieg aussehen könnte. Das ist keine Empfehlung.',
  'plan.entry': 'Möglicher Einstieg',
  'plan.entryHint': 'Preisbereich, in dem ein Kauf aus technischer Sicht Sinn ergeben könnte',
  'plan.stop': 'Verlustbremse (Stop-Loss)',
  'plan.stopHint': 'Verkaufsgrenze, um Verluste zu begrenzen, falls der Kurs fällt',
  'plan.target': 'Mögliches Kursziel {n}',
  'plan.targets': 'Mögliche Kursziele',
  'plan.riskReward': 'Chance im Vergleich zum Risiko',
  'plan.riskRewardHint': 'Reine Rechnung aus Einstieg, Verlustbremse und erstem Ziel, keine Vorhersage.',
  'plan.notComputable': 'nicht berechenbar',
  'plan.horizon': 'Zeitraum',
  'plan.noEntry': 'kein Einstieg sinnvoll',
  'plan.noStop': 'nicht festgelegt',
  'plan.vsPrice': '{pct} zum aktuellen Kurs',
  'horizon.kurzfristig': 'kurzfristig (Tage)',
  'horizon.mittelfristig': 'mittelfristig (Wochen)',
  'horizon.langfristig': 'langfristig (Monate)',
  'cand.entry_now': 'Aktueller Kursbereich',
  'cand.entry_pullback': 'Rücksetzer in die Unterstützungszone {zone}',
  'cand.entry_breakout': 'Ausbruch über die Widerstandszone {zone}',
  'cand.stop_atr': 'Etwas unterhalb des Kurses (2 × durchschnittliche Tagesspanne)',
  'cand.stop_support': 'Unter der Unterstützungszone {zone}',
  'cand.stop_breakout': 'Unter dem durchbrochenen Widerstand {zone}',
  'cand.target_zone': 'Widerstandszone {zone} (Unterkante)',
  'cand.target_high52': 'Höchststand der letzten 52 Wochen',
  'cand.target_atr2': 'Rechnerisch 2 × Tagesspanne über dem Kurs',
  'cand.target_atr4': 'Rechnerisch 4 × Tagesspanne über dem Kurs',
  'cand.target_atr_high52': 'Rechnerisch über dem Jahreshoch',
  'adv.analysis': 'Ausführliche Einschätzung',
  'adv.forTitle': 'Argumente für einen Einstieg',
  'adv.againstTitle': 'Argumente dagegen',
  'adv.risksTitle': 'Risiken',

  // Kennzahlen
  'tech.title': 'Kennzahlen',
  'tech.loading': 'Berechne Kennzahlen …',
  'tech.dataHint': 'Datenhinweis',
  'tech.trend': 'Trend',
  'tech.trendStructure': 'Trendstruktur',
  'tech.trendStructureHint': 'Steigende Hochs und Tiefs = Aufwärtstrend, fallende = Abwärtstrend. Swing-Hochs: {highs} · Swing-Tiefs: {lows}',
  'tech.smaCross': 'Kurzer vs. langer Durchschnitt',
  'tech.smaCrossAbove': 'SMA 50 über SMA 200',
  'tech.smaCrossBelow': 'SMA 50 unter SMA 200',
  'tech.golden': 'Golden Cross am {date} (vor {bars} Kerzen)',
  'tech.death': 'Death Cross am {date} (vor {bars} Kerzen)',
  'tech.noCross': 'Kein Kreuz im Datenzeitraum',
  'tech.averages': 'Durchschnittskurse',
  'tech.averageRow': 'SMA {n} / EMA {n}',
  'tech.averageHint': 'Kurs {pct} zum SMA',
  'tech.momentum': 'Schwung',
  'tech.macdBullCross': 'Bullisches Kreuz vor {bars} Kerzen',
  'tech.macdBearCross': 'Bärisches Kreuz vor {bars} Kerzen',
  'tech.histogram': 'Histogramm {value}',
  'tech.volatility': 'Schwankung',
  'tech.bollingerHint': '%B {pb} · Bandbreite {bw}',
  'tech.atrHint': '{pct} vom Kurs (durchschnittliche Tagesspanne)',
  'tech.volumeTitle': 'Handelsvolumen',
  'tech.volumeTrend': 'Volumentrend',
  'tech.volumeAvg': 'Ø20 {a} · Ø50 {b}',
  'tech.upDown': 'Handel an Plus- vs. Minustagen (20 Tage)',
  'tech.upDownHint': 'Über 1: An Tagen mit steigendem Kurs wurde mehr gehandelt',
  'tech.levels': 'Unterstützung und Widerstand',
  'tech.noLevels': 'Keine belastbaren Zonen gefunden.',
  'tech.noResistance': 'Keine belastbare Widerstandszone über dem Kurs (mindestens 2 Berührungen).',
  'tech.nextObstacle': 'Nächstes Hindernis: Höchststand der letzten 52 Wochen bei {high}.',
  'tech.nearHigh': 'Der Kurs liegt nahe am Hoch des Datenzeitraums.',
  'level.R': 'Widerstand {id}',
  'level.S': 'Unterstützung {id}',
  'level.I': 'Zone {id} (Kurs steckt drin)',
  'tech.touches': '{n} Berührungen',
  'tech.touch1': '1 Berührung',
  'tech.range52': '52-Wochen-Spanne',
  'tech.range52Partial': '52-Wochen-Spanne (nur {bars} Kerzen)',
  'tech.high52': '52-Wochen-Hoch',
  'tech.low52': '52-Wochen-Tief',
  'tech.belowHigh': 'Kurs {pct} darunter',
  'tech.aboveLow': 'Kurs {pct} darüber',
  'tech.footer': 'Alle Kennzahlen werden im Programm aus Tageskerzen berechnet, nicht von einer KI geschätzt. Die letzte Kerze kann während der Börsenzeit unvollständig sein.',
  'trend.aufwärts': 'aufwärts',
  'trend.abwärts': 'abwärts',
  'trend.seitwärts': 'seitwärts',
  'trend.unbekannt': 'unbekannt',
  'zone.überkauft': 'überkauft (stark gestiegen)',
  'zone.überverkauft': 'überverkauft (stark gefallen)',
  'zone.neutral': 'neutral',
  'zone.unbekannt': 'unbekannt',
  'macd.über Signal': 'über der Signallinie',
  'macd.unter Signal': 'unter der Signallinie',
  'macd.unbekannt': 'unbekannt',
  'vol.steigend': 'steigend',
  'vol.fallend': 'fallend',
  'vol.neutral': 'gleichbleibend',
  'vol.unbekannt': 'unbekannt',
  'hint.rsi': 'Misst, wie schnell der Kurs zuletzt gestiegen oder gefallen ist. Über 70 gilt als „heißgelaufen“, unter 30 als „stark gefallen“.',
  'hint.macd': 'Vergleicht einen kurzfristigen mit einem langfristigen Kurstrend. Liegt der Wert über der Signallinie, ist der Schwung eher positiv.',
  'hint.bollinger': 'Ein Band um den Durchschnittskurs. Berührt der Kurs den Rand, ist er ungewöhnlich weit vom Durchschnitt entfernt.',
  'hint.atr': 'Wie stark der Kurs an einem Tag typischerweise schwankt.',
  'hint.sma': 'Durchschnittskurs der letzten 20, 50 bzw. 200 Handelstage (SMA einfach, EMA gewichtet: neuere Tage zählen mehr).',

  // Glossar
  'gloss.title': 'Was bedeuten die Begriffe?',
  'gloss.sma': 'SMA / EMA: Durchschnittskurs der letzten Tage. Steigt der Kurs über den Durchschnitt, gilt das als Stärke.',
  'gloss.rsi': 'RSI: Zahl zwischen 0 und 100. Über 70 ist der Kurs zuletzt sehr schnell gestiegen, unter 30 sehr schnell gefallen.',
  'gloss.macd': 'MACD: Vergleicht zwei Durchschnitte, um den Schwung des Kurses zu zeigen.',
  'gloss.bollinger': 'Bollinger-Bänder: Ein Band um den Durchschnittskurs, das zeigt, wie weit der Kurs üblicherweise abweicht.',
  'gloss.atr': 'ATR: Durchschnittliche Tagesspanne, also wie stark der Kurs am Tag schwankt.',
  'gloss.support': 'Unterstützung / Widerstand: Preisbereiche, an denen der Kurs in der Vergangenheit oft gedreht hat, nach oben oder nach unten.',
  'gloss.cross': 'Golden Cross / Death Cross: Der kurze Durchschnitt (50 Tage) kreuzt den langen (200 Tage) nach oben bzw. nach unten.',
  'gloss.stop': 'Stop-Loss: Eine selbst gesetzte Verkaufsgrenze, um Verluste zu begrenzen.',
  'gloss.volume': 'Volumen: Wie viele Aktien gehandelt wurden. Viel Handel macht eine Kursbewegung glaubwürdiger.',

  // Nachrichten
  'news.loading': 'Lade Meldungen …',
  'news.rating': 'Die KI ordnet die Meldungen ein …',
  'news.summaryTitle': 'Kurz gesagt',
  'news.noSummary': 'Keine Zusammenfassung verfügbar.',
  'news.positive': 'Gut für die Aktie',
  'news.negative': 'Schlecht für die Aktie',
  'news.nothing': 'Nichts Belastbares in den Meldungen.',
  'news.listTitle': 'Meldungen',
  'news.noItems': 'Keine aktuellen Meldungen gefunden.',
  'news.allNoise': 'Alle Meldungen wurden als wenig wichtig eingestuft.',
  'news.showMore': '{n} weniger wichtige Meldungen einblenden',
  'news.showMore1': '1 weniger wichtige Meldung einblenden',
  'news.showLess': 'Weniger wichtige Meldungen ausblenden',
  'news.sourcesFailed': 'Nicht alle Quellen erreichbar: {sources}. Die Liste ist eventuell unvollständig.',
  'news.footnote': 'Meldungen in anderen Sprachen werden von der KI übersetzt (sobald die Einordnung vorliegt). Das Original steht darunter.',
  'news.original': 'Original',
  'news.kapTitle': 'Offizielle Meldungen (KAP)',
  'news.kapText': 'Pflichtmitteilungen der Firma auf der offiziellen Plattform KAP. Sie sind die verlässlichste Quelle und zählen bei der Einschätzung am meisten.',
  'news.pressTitle': 'Medien',
  'news.pressText': 'Berichte der Presse. Sie ergänzen die offiziellen Meldungen, sind aber oft Meinung oder Wiederholung.',
  'news.noKap': 'In diesem Zeitraum gab es keine offiziellen KAP-Meldungen.',
  'news.alsoReported': '+{n} weitere Berichte',
  'news.sortHint': 'Sortiert nach vermuteter Wirkung auf die Aktie, die wichtigsten zuerst.',
  'news.tapHint': 'Tippe auf eine Meldung: Die KI erklärt sie und ordnet ein, was sie für die Aktie bedeuten könnte.',
  'item.back': '‹ Alle Meldungen',
  'item.reading': 'Die KI liest die Meldung …',
  'item.gone': 'Diese Meldung steht nicht mehr in der Liste. Geh zurück und wähle sie erneut aus.',
  'item.summary': 'Kurz erklärt',
  'item.impact': 'Was das für die Aktie bedeuten könnte',
  'item.short': 'Kurzfristig (Tage bis Wochen)',
  'item.long': 'Langfristig (Monate bis Jahre)',
  'item.positives': 'Das könnte helfen',
  'item.negatives': 'Das könnte belasten',
  'item.watch': 'Worauf du achten kannst',
  'item.basisFull': 'Grundlage: der vollständige Text der KAP-Meldung.',
  'item.basisHeadline': 'Grundlage: nur die Überschrift (und ein Kurztext, falls vorhanden). Der Artikel selbst liegt der KI nicht vor, die Einschätzung ist deshalb grob.',
  'item.certainty': 'Wie gut ist die Einschätzung belegt? {level}',
  'item.note': 'Das ist eine Einordnung möglicher Wirkungen, keine Kursprognose und keine Empfehlung zum Kaufen oder Verkaufen.',
  'item.openKap': 'Meldung bei KAP öffnen ↗',
  'item.openOriginal': 'Originalartikel öffnen ↗',
  'impact.positiv': 'Eher gut für die Aktie',
  'impact.neutral': 'Eher neutral für die Aktie',
  'impact.negativ': 'Eher schlecht für die Aktie',
  'certainty.niedrig': 'eher dünn',
  'certainty.mittel': 'mittel',
  'certainty.hoch': 'gut belegt',
  'news.kapHint': 'Offizielle Pflichtmeldung des Unternehmens (KAP)',
  'news.category': 'Meldung',
  'sent.positiv': 'Positiv',
  'sent.neutral': 'Neutral',
  'sent.negativ': 'Negativ',
  'news.important': 'Wichtig',
  'news.sentimentUp': 'Positiv',
  'news.sentimentDown': 'Negativ',

  // Einstellungen
  'settings.title': 'Einstellungen',
  'settings.language': 'Sprache',
  'settings.languageHint': 'Gilt für die ganze App und für die Texte der KI.',
  'settings.access': 'Zugang',
  'settings.tokenLabel': 'Zugangscode (schützt deine Daten, wird nur auf diesem Gerät gespeichert)',
  'settings.tokenPlaceholder': 'Leer lassen, wenn keiner gesetzt ist',
  'settings.saveTest': 'Speichern und Verbindung testen',
  'settings.testing': 'Teste …',
  'settings.connectionOk': 'Verbindung OK',
  'settings.tokenAccepted': ' (Code akzeptiert)',
  'settings.noTokenNeeded': ' (kein Code nötig)',
  'settings.exampleQuote': ', Beispielkurs AAPL: {price}',
  'settings.connectionFailed': 'Verbindung fehlgeschlagen',
  'settings.checkToken': ' Bitte den Zugangscode prüfen.',
  'settings.aiTitle': 'KI-Einschätzung',
  'settings.aiActive': 'Aktiv: {providers}',
  'settings.aiDemo': '(Demo-Modus, keine echte KI)',
  'settings.aiMissing': 'Nicht eingerichtet. Auf dem Server fehlt ein KI-Schlüssel (GEMINI_API_KEY oder GROQ_API_KEY).',
  'settings.aiStorageSupabase': 'Zwischenspeicher: Supabase (dauerhaft).',
  'settings.aiStorageMemory': 'Zwischenspeicher: nur Arbeitsspeicher des Servers.',
  'settings.aiStorageWarn': ' Ohne Supabase gehen Auswertungen bei Kaltstarts verloren und verbrauchen das Gratis-Kontingent schneller.',
  'settings.backupTitle': 'Meine Liste sichern',
  'settings.backupText':
    'Deine Aktienliste liegt in diesem Browser bzw. dieser installierten App ({count}). Die App auf dem Home-Bildschirm hat einen eigenen Speicher: exportiere die Liste im Safari-Browser und importiere sie in der App.',
  'settings.exportBtn': 'Exportieren (kopieren)',
  'settings.importPlaceholder': 'Export hier einfügen und importieren',
  'settings.importAria': 'Import-Text',
  'settings.importBtn': 'Importieren (ersetzt die Liste)',
  'settings.copied': 'Liste in die Zwischenablage kopiert.',
  'settings.copyFailed': 'Kopieren nicht möglich: Der Text steht unten und kann von dort markiert werden.',
  'settings.imported': '{n} importiert.',
  'settings.importFailed': 'Der Text ist kein gültiger Export. Es wurde nichts geändert.',
  'settings.count.one': '1 Aktie',
  'settings.count.many': '{n} Aktien',
  'settings.aboutTitle': 'Woher kommen die Daten?',
  'settings.about1': 'Kurse und Kerzen: Yahoo Finance (inoffiziell), bei Ausfall İş Yatırım (BIST, nur Tagesschluss), US-Live-Kurse optional über Finnhub.',
  'settings.about2': 'Kurse von BIST und XETRA sind ca. 15 Minuten verzögert. Für BIST gibt es kostenlos keine Echtzeitquelle.',
  'settings.about3': 'Nachrichten: KAP (Pflichtmeldungen der BIST-Firmen) und Google News.',
  'settings.about4': 'Alle Kennzahlen werden im Programm berechnet. Die KI (Gemini, ersatzweise Groq) schreibt nur den erklärenden Text und darf keine Zahlen erfinden: Kurse wählt sie aus berechneten Vorschlägen, andere Zahlen werden gegen die Eingabedaten geprüft.',
  'settings.version': 'Version 0.5 · einfache Ansicht, Deutsch und Türkisch',

  // Hinweis
  'disclaimer.strong': 'Keine Anlageberatung.',
  'disclaimer.text': 'Alle Angaben dienen nur der Information, sind ohne Gewähr und können verzögert oder fehlerhaft sein. Kursgewinne der Vergangenheit sagen nichts über die Zukunft aus.',
} as const;

export type DictKey = keyof typeof de;
